{{- if .Values.metrics }}
{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "chatbot.fullname" . }}
  labels:
    {{- include "chatbot.labels" . | nindent 4 }}
    {{- if .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.metrics.serviceMonitor.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: {{ .Values.service.port }}
      path: /metrics
      interval: {{ .Values.metrics.interval | default "30s" }}
      scrapeTimeout: {{ .Values.metrics.scrapeTimeout | default "10s" }}
      {{- if .Values.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml .Values.metrics.serviceMonitor.metricRelabelings | nindent 6 }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml .Values.metrics.serviceMonitor.relabelings | nindent 6 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "chatbot.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
