apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki.monitoring.svc:3100
        access: proxy
        
      - name: Prometheus
        type: prometheus
        url: http://prometheus.monitoring.svc:9090
        access: proxy
        isDefault: true
        
      - name: Jaeger
        type: jaeger
        url: http://jaeger-query.monitoring.svc:16686
        access: proxy
        jsonData:
          tracesToLogs:
            datasourceUid: loki
            tags: ['job', 'instance', 'pod']
